export const SET_AUTH_USER = 'SET_AUTH_USER';

export const EDIT_CHALLENGE = 'EDIT_CHALLENGE';
export const REMOVE_CHALLENGE = 'REMOVE_CHALLENGE';
export const ADD_CHALLENGES = 'ADD_CHALLENGES';
export const ADD_CHALLENGE_ATHLETES = 'ADD_CHALLENGE_ATHLETES';

export const SET_ERROR = 'SET_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';

export const GET_ATHLETE_CLUBS = 'GET_ATHLETE_CLUBS';
