export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_CLUB_MEMBERS = 'SET_CLUB_MEMBERS';

export const SET_CHALLENGE = 'SET_CHALLENGE';
export const FOLLOW_CHALLENGE = 'FOLLOW_CHALLENGE';

export const SET_CHALLENGE_ATHLETE_INFO = 'SET_CHALLENGE_ATHLETE_INFO';
export const SET_CHALLENGE_ATHLETE_ACTIVITIES = 'SET_CHALLENGE_ATHLETE_ACTIVITIES';
